config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  devise_for :users
  resources :events do
  	resources :attendances, only:[:new, :create, :destroy, :index]
  end
  resources :users, only:[:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
	#after_create :validation_send

  	belongs_to :event
  	belongs_to :user

 	def validation_send
  	UserMailer.validation_email(self.event, self.user).deliver_now
  	end

end

app/models/event.rb
class Event < ApplicationRecord
	has_one_attached :picture

	belongs_to :user
	has_many :attendances
	has_many :users, through: :attendances

	validates :picture, presence: true
	validates :start_date, presence: true
	validates :duration, presence: true, numericality: { greater_than: 0}
	validates :title, presence: true, length: { in: 5..140 }
	validates :description, presence: true, length: { in: 20..1000 }
	validates :price, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 1000 }
	validates :location, presence: true
	validate :start_date_cannot_be_in_the_past

	def start_date_cannot_be_in_the_past
		if !start_date.blank? && start_date < Date.today
      	errors.add(:start_date, "can't be in the past")
    	end
	end

	def duration_must_be_multiple_of_5
		unless (duration % 5) == 0
		errors.add(:duration, "must be a mutiple of 5")
		end
	end

	def self.end_date(event)
		event.start_date + event.duration
	end
		
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  has_one_attached :avatar

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	#after_create :welcome_send

	has_many :events
	has_many :attendances
	has_many :events, through: :attendances

	validates :email, presence: true, uniqueness: true

	def welcome_send
		UserMailer.welcome_email(self).deliver_now
	end

  	def is_already_attending?(event)
  		participants_id = event.attendances.pluck("user_id")
  		participants_id.include?(self.id.to_i) ? true : false
  	end

  	def is_already_admin?(event)
  		event.user.id.to_i == self.id.to_i ? true : false
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_devise_parameters, if: :devise_controller?

	def configure_devise_parameters
	  devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation)}
	  devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)}
	end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create]

	def new
		if 
		@attendance = Attendance.new
		@event = Event.find(params[:event_id])
		@user = current_user
	end

	def index
		@attendances = Event.find(params[:event_id]).attendances
		@event = Event.find(params[:event_id])
	end

	def create

	  @event = Event.find(params[:event_id])

	  @amount = @event.price*100

	  customer = Stripe::Customer.create({
	    email: params[:stripeEmail],
	    source: params[:stripeToken],
	  })

	  charge = Stripe::Charge.create({
	    customer: customer.id,
	    amount: @amount,
	    description: 'Rails Stripe customer',
	    currency: 'eur',
	  })

	  @attendance = Attendance.new(user_id: current_user.id.to_i, event_id: @event.id.to_i, stripe_customer_id: customer.id.to_i)

	  if @attendance.save
			flash[:success] = "Paiement accepté ! Vous êtes maintenant inscrit à l'évènement"
			redirect_to event_path(@event.id)
		else
			redirect_to new_event_attendance_path(@event.id)
			flash[:error] = "Le paiement a échoué"
		end

	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to new_event_charge_path
	end

	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create]
  before_action :is_admin?, only: [:update, :destroy, :edit]

  def index
  	@events = Event.all
  end

  def new
  	@event = Event.new
  end

  def create
  	@event = Event.new(
  		start_date: params[:start_date], 
  		user_id: current_user.id,
  		duration: params[:duration],
  		title: params[:title],
  		description: params[:description],
  		price: params[:price],
  		location: params[:location], 
      picture: params[:picture]
  		)

  	if @event.save
      @event.picture.attach(params[:picture])
  		redirect_to event_path(@event.id)
  	else
  		redirect_to new_event_path, flash: { error: "Informations éronnées!" }
  	end
  end

  def show
  	@event = Event.find(params[:id])
  	@end_date = Event.end_date(Event.find(params[:id]))
  end

  def edit
    @event = @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(
      start_date: params[:start_date], 
      user_id: current_user.id,
      duration: params[:duration],
      title: params[:title],
      description: params[:description],
      price: params[:price],
      location: params[:location], 
      )
    redirect_to event_path(params[:id]), notice: "Well done! You successfully edited the event! "
    else
    render :edit
    end
  end

  private

  def event_params
    params.require(:event).permit(:start_date, :user_id, :duration, :title, :price, :description, :location, :picture)
  end

  def is_admin?
    @event = @event = Event.find(params[:id])
    @event.user.id.to_i == current_user.id.to_i ? true : false
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, only: [:show]
	before_action :is_the_owner_of_the_page?, only: [:show]

	def show
		@user = User.find(params[:id])
		@events = Event.where(user_id: params[:id])
	end

	private

  	def is_the_owner_of_the_page?
  		unless current_user.id.to_i == params[:id].to_i
  		redirect_to events_path
  		end
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/event_pictures_helper.rb
module EventPicturesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendances/index.html.erb
    <div class="container">
      <br><br>
      <div class="my-3 p-3 bg-white rounded box-shadow">
        <h6 class="border-bottom border-gray pb-2 mb-0">Liste des participants</h6>
        
        <% if !@attendances.nil? %>

          <% @attendances.each do |attendance|%>
          <div class="media text-muted pt-3">
            <img data-src="holder.js/32x32?theme=thumb&bg=007bff&fg=007bff&size=1" alt="" class="mr-2 rounded">
            <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
              <div class="d-flex justify-content-between align-items-center w-100">
                <strong class="text-gray-dark"><%= attendance.user.first_name + " " + attendance.user.last_name %></strong>
              </div>
              <span class="d-block">Inscription le <%=attendance.created_at.strftime("%F")%> à <%=attendance.created_at.strftime("%HH%M")%></span>
            </div>
          </div>
          <%end%>

        <% else %>

          <div class="media text-muted pt-3">
            <img data-src="holder.js/32x32?theme=thumb&bg=007bff&fg=007bff&size=1" alt="" class="mr-2 rounded">
            <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
              <div class="d-flex justify-content-between align-items-center w-100">
                <strong class="text-gray-dark">Vous n'avez pas encore de participant</strong>
              </div>
            </div>
          </div>

        <%end%>
        <br><br>

      <div class="row">
        <div class="col-md-3">
          <%=link_to "Éditer l'évènement", edit_event_path(params[:event_id]), class: "btn btn-md btn-primary"%>
        </div>
      </div>
    </div>

app/views/attendances/new.html.erb
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br><br>
        <h1 class="h3 mb-3 font-weight-normal text-center">Check Out</h1>

        <div class="card-body">
          <h1 class="card-title pricing-card-title"> <%= @event.title %></h1>
          <ul class="list-unstyled mt-3 mb-4">
                <hr>
                <li>Location: <%= @event.location %> </li>
                <hr>
                <li>Start Date: <%= @event.start_date %> </li>
                <hr>
              </ul>
        </div>
          <%= form_tag event_attendances_path(@event.id) do %>
            <article>
              <% if flash[:error].present? %>
                <div id="error_explanation">
                  <p><%= flash[:error] %></p>
                </div>
              <% end %>
              <label class="amount">
                <span><h4 class="card-title pricing-card-title">Amount to pay: <%= @event.price %>€ </h4></span>
              </label>
            </article>

            <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                    data-description="Payment of <% @user.first_name + @user.last_name%>"
                    data-amount="<%= @event.price*100 %>"
                    data-locale="auto"></script>
          <% end %>
    </div>
  </div>
</div>
</div>

app/views/events/edit.html.erb
<% flash.each do |msg| %>
  <div class="alert alert-warning">
    <%= msg[1] %>
  </div>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
    <br><br><br>
      <h1 class="h3 mb-3 font-weight-normal text-center">Edit your Event</h1>
      <%= form_tag url_for(action: 'update'), multipart: true, method: "patch" do %>

        <div class="form-group">
          <%= label_tag :title, "Title"%><br/>
          <%= text_field_tag :title, @event.title, placeholder: "Between 5 and 140 characters...", maxlength: 140, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= label_tag :description, "Description"%><br/>
          <%= text_area_tag :description, @event.description, placeholder: "Between 20 and 1000 characters...", class: "form-control" %>
        </div>

        <div class="form-group">
          <%= label_tag :location, "Location"%><br/>
          <%= text_field_tag :location, @event.location, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= label_tag :price, "Price"%><br/>
          <%= number_field_tag :price, @event.price,placeholder: "Between 1€ and 1000€", max: 1000, min: 1, class: "form-control" %>
        </div>

       <div class="form-group">
          <%= label_tag :duration, "Duration (min)"%><br/>
          <%= number_field_tag :duration, @event.duration, min: 0, step: 5, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= label_tag :start_date, "Start Date"%><br/>
          <%= date_field_tag :start_date, Date.today, class: "form-control" %>
        </div>
        <hr>
        <div class="form-group">
        <%= label_tag :picture, "Ajouter un photo à l'évènement"%><br/>
        <%= file_field_tag :picture %>
        </div>
        <hr>
        <div class="actions">
          <%= submit_tag "Edit Event", class: "btn btn-lg btn-primary btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class="jumbotron">
  <div class="container">
     <h1 class="display-3">Sortir. Partager. Découvrir.</h1>
     <p>Eventbrite rapproche les gens grâce à des expériences en direct. Découvrez des événements qui correspondent à vos passions ou créez votre propre événement avec les outils de billetterie en ligne.</p>
     <p><%= link_to "Créer un évènement", new_event_path, class: "btn btn-primary btn-lg" %></p>
  </div>
</div>

<main role="main">
  <div class="container">
    <div class="row">
      <% @events.each do |event| %>
        <div class="col-md-4" style="text-align: justify">
        <h2 class="card-title"><%= event.title%></h2>
        <% unless event.user.nil? %>
          <h6 class="card-subtitle mb-2 text-muted">Organized by <%= event.user.first_name + " " + event.user.last_name%></h6>
        <% end %>
        <p> <%= event.description %> </p>
        <p><%= link_to "View details", event_path(event.id), class: "btn btn-secondary" %></p>
        </div>
        <% end %>
    </div>
  </div> 
</main>

app/views/events/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
    <br><br><br>
      <h1 class="h3 mb-3 font-weight-normal text-center">Create your Event</h1>
      <%= form_tag url_for(action: 'create'), method: "post" do %>

        <div class="form-group">
          <%= label_tag :title, "Title"%><br/>
          <%= text_field_tag :title, "", placeholder: "Between 5 and 140 characters...", maxlength: 140, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= label_tag :description, "Description"%><br/>
          <%= text_area_tag :description, "", placeholder: "Between 20 and 1000 characters...", class: "form-control" %>
        </div>

        <div class="form-group">
          <%= label_tag :location, "Location"%><br/>
          <%= text_field_tag :location, "", class: "form-control" %>
        </div>

        <div class="form-group">
          <%= label_tag :price, "Price"%><br/>
          <%= number_field_tag :price, "",placeholder: "Between 1€ and 1000€", max: 1000, min: 1, class: "form-control" %>
        </div>

       <div class="form-group">
          <%= label_tag :duration, "Duration (min)"%><br/>
          <%= number_field_tag :duration, "", min: 0, step: 5, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= label_tag :start_date, "Start Date"%><br/>
          <%= date_field_tag :start_date, Date.today, class: "form-control" %>
        </div>
        <div class="actions">
          <%= submit_tag "Create Event", class: "btn btn-lg btn-primary btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
      <% unless @event.user.nil? %>
      <h1 class="display-4"><%= @event.title %></h1>
      <p class="lead"> <%= @event.description %> </p>
      
      <%if @event.picture.attached?%>
        <%= image_tag @event.picture, alt: 'picture' %>
      <%else%>
        <p>=== Il n'y a pas encore de photo lié à cet évènement ===</p>
      <%end%>
 
      <% else %>
      <h1 class="display-4"><%= @event.title %> (ANNULÉ!)</h1>
      <p class="lead"> <%= @event.description %> </p>
      <p class="lead"> Sniff...L'organisateur a annulé l'évènement </p>
      <% end %>

    </div>

    <div class="container">
      <div class="card-deck mb-3 text-center">
        <div class="card mb-4 box-shadow">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal"> Details </h4>
          </div>

          <% unless @event.user.nil? %>

            <div class="card-body">
              <h1 class="card-title pricing-card-title">$ <%= @event.price %> </h1>
              <ul class="list-unstyled mt-3 mb-4">
                <hr>
                <li>Number of participants: <%= @event.attendances.count %> </li>
                <hr>
                <li>Organisation contact: <%= @event.user.email %> </li>
                <hr>
                <li>Location: <%= @event.location %> </li>
                <hr>
                <li>Start Date: <%= @event.start_date %> </li>
                <hr>
                <li>End Date: <%= @end_date %> </li>
              </ul>

              <% if !user_signed_in? %>
                <%=link_to "Register Now", new_event_attendance_path(@event.id), class: "btn btn-lg btn-block btn-primary"%>  
              <% elsif !current_user.is_already_attending?(@event) && !current_user.is_already_admin?(@event)%>
                <%=link_to "Register Now", new_event_attendance_path(@event.id), class: "btn btn-lg btn-block btn-primary"%> 
              <% elsif current_user.is_already_attending?(@event) %>
                <%=link_to "Vous participez déjà à cet évènement", "" , class: "btn btn-lg btn-block btn-secondary"%>
              <%else%>
                <%=link_to "Mon espace évènement", event_attendances_path(@event.id), class: "btn btn-lg btn-block btn-primary"%> 
              <% end %> 
            </div>

          <% else %>

          <div class="card-body">
            <h1 class="card-title pricing-card-title"> Évènement annulé </h1>
          </div>

          <% end %>
        </div>
      </div>
      <%= link_to "Back", :back %>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbride</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </head>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="/">Eventbride</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <%= link_to "Créer un évènement", new_event_path, method: :get, class: "nav-link"%>
          </li>
        </ul>
        <% if user_signed_in? %>
            <a class="nav-item nav-link active"><%= link_to "Mon Profil", user_path(current_user.id), method: :get , class: 'btn btn-primary'%></a>
            <a class="nav-item nav-link active"><%= link_to "Se déconnecter", destroy_user_session_path, method: :delete , class: 'btn btn-secondary'%></a>
          <%else%>
            <a class="nav-item nav-link active"><%= link_to "Sign in", new_user_session_path, method: :get, class: 'btn btn-primary'%></a>
            <a class="nav-item nav-link active"><%= link_to "Sign Up", new_user_registration_path, method: :get, class: 'btn btn-secondary'%></a>
          <% end %>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<div class="container" style="width: 100em; height: 100px; margin: 5em auto">
  <div class="row" style="justify-content:center">
    <div class="col-md-9">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= @user.first_name%> <%= @user.last_name%></h5>
          <p class="card-text"><%= @user.description%></p>
        </div>
        <ul class="list-group list-group-flush">
          
          <li class="list-group-item">First Name: <%= @user.first_name%> </li>
          <li class="list-group-item">Last Name: <%= @user.last_name%> </li>
          <li class="list-group-item">Email: <%= @user.email%></li>
        </ul>
        <div class="card-body">
          <%= link_to "Edit your profil", edit_user_registration_path, class: "card-link" %>
        </div>
      </div>
      <br><br>
    </div>
  </div>
  <h4 class="display">Les évènements que tu organises:</h4>
  <br>
  <div class="row" style="justify-content:start">
    <% @events.each do |event|%>
      <div class="col-md-3">
        <div class="card" style="width: 18rem">
          <div class="card-body">
            <h5 class="card-title"><%= event.title%></h5>
            <h6 class="card-subtitle mb-2 text-muted"> At <%= event.location%></h6>
            <p class="card-text"><%= event.description%></p>
            <%= link_to "View more", event_path(event.id), class: "card-link" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>